CREATE TABLE reaction
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    target_type VARCHAR(20)  NOT NULL,
    target_id   BIGINT       NOT NULL,
    member_id   BIGINT       NOT NULL,
    type       VARCHAR(20)  NOT NULL,
    status     VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE reaction
    ADD CONSTRAINT fk_member FOREIGN KEY (member_id) REFERENCES member (id);

ALTER TABLE reaction
    ADD CONSTRAINT unique_reaction UNIQUE (target_type, target_id, member_id, type);