CREATE TABLE IF NOT EXISTS exam_comment
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content           TEXT         NOT NULL,
    exam_id           BIGINT       NOT NULL,
    member_id         BIGINT       NOT NULL,
    parent_comment_id BIGINT,
    deleted_at        TIMESTAMP(6),
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_exam_comment_exam FOREIGN KEY (exam_id) REFERENCES exam (id),
    CONSTRAINT fk_exam_comment_member FOREIGN KEY (member_id) REFERENCES member (id)
);

CREATE INDEX idx_exam_comment_exam_id ON exam_comment (exam_id);
CREATE INDEX idx_exam_comment_member_id ON exam_comment (member_id);
CREATE INDEX idx_exam_comment_parent_comment_id ON exam_comment (parent_comment_id);
