CREATE TABLE comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content    TEXT         NOT NULL,
    exam_id    BIGINT       NOT NULL,
    member_id  BIGINT       NOT NULL,
    deleted_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE comment
    ADD CONSTRAINT fk_exam FOREIGN KEY (exam_id) REFERENCES exam (id);

ALTER TABLE comment
    ADD CONSTRAINT fk_member FOREIGN KEY (member_id) REFERENCES member (id);

