spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: create-drop

api-host: http://localhost:8080
client-host: http://localhost:5173

auth:
  jwt:
    secret-key: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6
    expiration-time: 86400000 # 1 day
  cookie:
    access-token-key: access_token
    httpOnly: true
    secure: true
    domain: localhost
    path: /
    maxAge: 86400 # 1 day
  oauth2:
    github:
      client-id: ${OAUTH_GITHUB_CLIENT_ID}
      client-secret: ${OAUTH_GITHUB_CLIENT_SECRET}
      redirect-uri: ${api-host}/api/v1/auth/oauth2/callback/github
      client-uri: ${client-host}
    google:
      client-id: ${OAUTH_GOOGLE_CLIENT_ID}
      client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
      redirect-uri: ${api-host}/api/v1/auth/oauth2/callback/google
      client-uri: ${client-host}

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.orm.transaction: DEBUG
    org.hibernate.orm.jdbc.bind: trace
