spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:database
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true

auth:
  cookie:
    access-token-key: access_token
    httpOnly: true
    secure: false
    domain: localhost
    maxAge: 86400 # 1 day

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.orm.transaction: DEBUG
    org.hibernate.orm.jdbc.bind: trace
