spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: fluffy-redis
      port: 6379
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true

api-host: https://api.fluffy.run
client-host: https://www.fluffy.run

auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 86400000 # 1 day
  cookie:
    access-token-key: access_token
    httpOnly: true
    secure: true
    domain: .fluffy.run
    path: /
    maxAge: 86400 # 1 day
  oauth2:
    github:
      client-id: ${OAUTH_GITHUB_CLIENT_ID}
      client-secret: ${OAUTH_GITHUB_CLIENT_SECRET}
      redirect-uri: ${api-host}/api/v1/auth/oauth2/callback/github
      client-uri: ${client-host}
    google:
      client-id: ${OAUTH_GOOGLE_CLIENT_ID}
      client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
      redirect-uri: ${api-host}/api/v1/auth/oauth2/callback/google
      client-uri: ${client-host}

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.orm.transaction: DEBUG
    org.hibernate.orm.jdbc.bind: trace
