name: 버그 신고
description: 버그를 신고해주세요.
labels: ['Bug']
body:
  - type: markdown
    attributes:
      value: |
        버그 신고를 작성해주셔서 감사합니다! 🙏 여러분의 소중한 피드백이 시스템 개선에 큰 도움이 됩니다.
  - type: textarea
    id: what-happened
    attributes:
      label: 어떤 일이 발생했나요? 🤔
      description: 문제가 발생한 상황을 자세히 설명해주세요. 어떤 결과를 기대하셨는지도 함께 적어주세요.
      placeholder: 예상치 못한 버그가 발생했습니다...
    validations:
      required: true
  - type: textarea
    id: what-caused
    attributes:
      label: 왜 발생했을까요?
      description: 문제의 원인에 대한 개인적인 생각이나 추측을 적어주세요.
      placeholder: 제 생각에는...
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 관련 로그 또는 오류 메시지
      description: 문제와 관련된 로그나 오류 메시지를 복사하여 붙여넣어주세요. 코드 형식으로 자동 서식이 지정됩니다.
      render: shell
  - type: file
    id: screenshot
    attributes:
      label: 스크린샷 첨부
      description: 문제가 발생한 화면의 스크린샷을 첨부해주세요. (선택 사항)
  - type: checkboxes
    id: terms
    attributes:
      label: 동의 👍
      description: 아래 항목을 모두 확인하고 체크해주세요.
      options:
        - label: 다른 이슈가 있는지 확인했습니다. ✅
          required: true
