services:
  app:
    container_name: fluffy-app
    image: ${DOCKER_APP_IMAGE}
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: prod
    restart: always
  redis:
    container_name: fluffy-redis
    image: redis:7.4.1
    restart: always
    ports:
      - '6379:6379'
