x-app: &app
  image: ${DOCKER_APP_IMAGE}
  env_file:
    - .env
  environment:
    TZ: Asia/Seoul
    SPRING_PROFILES_ACTIVE: prod
  restart: always

services:
  # app1 (blue & green)
  app1-blue:
    <<: *app
    container_name: app1-blue
    ports:
      - '8080:8080'
      - '8090:8082'
  app1-green:
    <<: *app
    container_name: app1-green
    ports:
      - '8081:8080'
      - '8091:8082'

  # app2 (blue & green)
  app2-blue:
    <<: *app
    container_name: app2-blue
    ports:
      - '8082:8080'
      - '8092:8082'
  app2-green:
    <<: *app
    container_name: app2-green
    ports:
      - '8083:8080'
      - '8093:8082'
