name: Server CI

on:
  push:
    branches: [main]
    paths: ['server/**']
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths: ['server/**']

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build
